# For unknown reasons, the port must be set, although it will be replaced by the discovery server
server:
  port: 9999
spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  application:
    name: poc-mongo-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
